# Generated by Django 6.0.6 on 2026-07-21 05:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('brand_type', models.CharField(choices=[('own', 'Our Brand'), ('competitor', 'Competitor Brand')], default='own', max_length=12)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/')),
                ('is_active', models.BooleanField(default=True)),
                ('contact_person', models.CharField(blank=True, help_text="Competitor's local rep/contact, if known.", max_length=120)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('market_strength', models.CharField(blank=True, choices=[('weak', 'Weak'), ('moderate', 'Moderate'), ('strong', 'Strong')], max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Market intel / notes about this competitor.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('link_name', models.CharField(blank=True, help_text='URL name, e.g. tracker:turnover_create', max_length=100)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('sku', models.CharField(blank=True, max_length=60)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='tracker.brand')),
            ],
            options={
                'ordering': ['brand__name', 'name'],
                'unique_together': {('brand', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('owner_name', models.CharField(blank=True, max_length=150)),
                ('contact_person', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('counter_type', models.CharField(choices=[('retail', 'Retail Shop'), ('wholesale', 'Wholesale Counter'), ('hardware', 'Hardware Store'), ('showroom', 'Showroom'), ('other', 'Other')], default='retail', max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealers', to='accounts.area')),
                ('assigned_salesmen', models.ManyToManyField(blank=True, related_name='assigned_dealers', to=settings.AUTH_USER_MODEL)),
                ('brands_dealt', models.ManyToManyField(blank=True, related_name='dealers', to='tracker.brand')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealers_created', to=settings.AUTH_USER_MODEL)),
                ('products_dealt', models.ManyToManyField(blank=True, related_name='dealers', to='tracker.product')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('project_type', models.CharField(choices=[('construction', 'Construction Site'), ('bulk_client', 'Bulk Client'), ('government', 'Government Project'), ('institutional', 'Institutional'), ('other', 'Other')], default='construction', max_length=20)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=120)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('stage', models.CharField(choices=[('lead', 'Lead / Prospect'), ('negotiation', 'Negotiation'), ('finalized', 'Finalized'), ('execution', 'Under Execution'), ('lost', 'Lost')], default='lead', max_length=20)),
                ('expected_business_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('visit_date', models.DateField(default=django.utils.timezone.now)),
                ('expected_closure_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='project_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_visits', to='accounts.area')),
                ('salesman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('check_in_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('check_in_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('check_out_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='visit_photos/')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='tracker.dealer')),
                ('salesman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-check_in_time'],
            },
        ),
        migrations.CreateModel(
            name='Turnover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnovers', to='tracker.brand')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnovers', to='tracker.dealer')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnovers', to='tracker.product')),
                ('salesman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnovers', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnovers', to='tracker.visit')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductAwareness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_in_stock', models.BooleanField(default=True)),
                ('stock_quantity_estimate', models.PositiveIntegerField(blank=True, null=True)),
                ('display_quality', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor')], default='good', max_length=10)),
                ('is_visible_to_customer', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='awareness_photos/')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awareness_records', to='tracker.dealer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awareness_records', to='tracker.product')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awareness_recorded', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='awareness_records', to='tracker.visit')),
            ],
            options={
                'verbose_name': 'Product Awareness Record',
                'verbose_name_plural': 'Product Awareness Records',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('our_discount_percent', models.DecimalField(decimal_places=2, default=0, help_text='Discount % offered on our product.', max_digits=5)),
                ('competitor_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('competitor_discount_percent', models.DecimalField(decimal_places=2, default=0, help_text='Discount % offered on competitor product.', max_digits=5)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_records', to='tracker.dealer')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_records_recorded', to=settings.AUTH_USER_MODEL)),
                ('competitor_product', models.ForeignKey(blank=True, limit_choices_to={'brand__brand_type': 'competitor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competitor_price_records', to='tracker.product')),
                ('our_product', models.ForeignKey(limit_choices_to={'brand__brand_type': 'own'}, on_delete=django.db.models.deletion.CASCADE, related_name='our_price_records', to='tracker.product')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_records', to='tracker.visit')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
